# Generated by Django 5.2.5 on 2025-08-31 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_deleted_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_messages', through='chat.MessageReadReceipt', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='messagereadreceipt',
            index=models.Index(fields=['message', 'user'], name='chat_messag_message_62db1e_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereadreceipt',
            index=models.Index(fields=['read_at'], name='chat_messag_read_at_2d1afa_idx'),
        ),
        migrations.AddField(
            model_name='chatreadstatus',
            name='last_read_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.message'),
        ),
        migrations.AddField(
            model_name='chatreadstatus',
            name='private_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.privatechat'),
        ),
        migrations.AddField(
            model_name='chatreadstatus',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.room'),
        ),
        migrations.AddField(
            model_name='chatreadstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chatreadstatus',
            index=models.Index(fields=['user', 'private_chat'], name='chat_chatre_user_id_5024db_idx'),
        ),
        migrations.AddIndex(
            model_name='chatreadstatus',
            index=models.Index(fields=['user', 'room'], name='chat_chatre_user_id_0b10e4_idx'),
        ),
        migrations.AddIndex(
            model_name='chatreadstatus',
            index=models.Index(fields=['updated_at'], name='chat_chatre_updated_fcafde_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatreadstatus',
            unique_together={('user', 'private_chat'), ('user', 'room')},
        ),
    ]
