# Generated by Django 5.2.5 on 2025-09-06 15:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_otpverification_passwordresetrequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Your full name', max_length=100)),
                ('email', models.EmailField(help_text="We'll use this to respond to you", max_length=254)),
                ('ticket_type', models.CharField(choices=[('general', 'General Inquiry'), ('technical', 'Technical Issue'), ('feature', 'Feature Request'), ('bug', 'Bug Report'), ('account', 'Account Issue'), ('privacy', 'Privacy Concern'), ('other', 'Other')], default='general', max_length=20)),
                ('subject', models.CharField(help_text='Brief description of your issue', max_length=200)),
                ('message', models.TextField(help_text='Detailed description of your query or issue')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('user_agent', models.TextField(blank=True, help_text='Browser and device information')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('page_url', models.URLField(blank=True, help_text='Page where the issue occurred')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for administrators')),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support Ticket',
                'verbose_name_plural': 'Support Tickets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'priority'], name='chat_suppor_status_84af83_idx'), models.Index(fields=['created_at'], name='chat_suppor_created_e87894_idx'), models.Index(fields=['email'], name='chat_suppor_email_52ea12_idx'), models.Index(fields=['ticket_type'], name='chat_suppor_ticket__8a6d65_idx')],
            },
        ),
    ]
